import '../models/app_user.dart';
import '../models/concert.dart';

String _escapeHtml(String value) {
  return value
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&#39;');
}

String _formatDate(DateTime? date) {
  if (date == null) return 'Date unknown';
  const months = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  ];
  return '${months[date.month - 1]} ${date.day}, ${date.year}';
}

/// Renders a standalone, self-contained HTML page showing [user]'s concert
/// stats, styled to match the app's beige/brown theme.
String buildStatsHtml({required AppUser user, required List<Concert> attendedConcerts}) {
  final artistCount = attendedConcerts.map((c) => c.displayArtist).toSet().length;
  final sorted = [...attendedConcerts]
    ..sort((a, b) => (b.date ?? DateTime(0)).compareTo(a.date ?? DateTime(0)));

  final rows = sorted.map((c) {
    return '''
      <li class="concert">
        <div class="concert-name">${_escapeHtml(c.displayArtist)}</div>
        <div class="concert-meta">${_escapeHtml(_formatDate(c.date))} &middot; ${_escapeHtml(c.venueName)}${c.city.isNotEmpty ? ' - ${_escapeHtml(c.city)}' : ''}</div>
      </li>''';
  }).join();

  final emptyState = attendedConcerts.isEmpty
      ? '<p class="empty">No concerts marked as attended yet.</p>'
      : '';

  return '''
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${_escapeHtml(user.name)}'s Concert Stats</title>
<style>
  body {
    margin: 0;
    padding: 32px 16px;
    background: #F7F1E3;
    color: #3B2A20;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  }
  .card {
    max-width: 480px;
    margin: 0 auto;
    background: #FFFFFF;
    border-radius: 16px;
    padding: 24px;
    box-shadow: 0 4px 16px rgba(74, 46, 35, 0.12);
  }
  h1 {
    font-size: 22px;
    margin: 0 0 4px;
    text-align: center;
  }
  .subtitle {
    text-align: center;
    color: rgba(59, 42, 32, 0.7);
    margin: 0 0 24px;
    font-size: 14px;
  }
  .stats {
    display: flex;
    gap: 12px;
    margin-bottom: 24px;
  }
  .stat {
    flex: 1;
    background: rgba(233, 223, 201, 0.6);
    border-radius: 12px;
    padding: 16px 8px;
    text-align: center;
  }
  .stat-value {
    font-size: 28px;
    font-weight: 700;
  }
  .stat-label {
    font-size: 13px;
    color: rgba(59, 42, 32, 0.7);
    margin-top: 4px;
  }
  h2 {
    font-size: 15px;
    margin: 0 0 8px;
  }
  ul.concert-list {
    list-style: none;
    margin: 0;
    padding: 0;
  }
  .concert {
    background: rgba(233, 223, 201, 0.4);
    border-radius: 10px;
    padding: 10px 12px;
    margin-bottom: 8px;
  }
  .concert-name {
    font-weight: 700;
  }
  .concert-meta {
    font-size: 12px;
    color: rgba(59, 42, 32, 0.7);
    margin-top: 2px;
  }
  .empty {
    text-align: center;
    color: rgba(59, 42, 32, 0.5);
    font-size: 14px;
  }
  .footer {
    text-align: center;
    font-size: 12px;
    color: rgba(59, 42, 32, 0.4);
    margin-top: 24px;
  }
</style>
</head>
<body>
  <div class="card">
    <h1>${_escapeHtml(user.name)}'s Concert Stats</h1>
    <p class="subtitle">on Encore 🎤</p>
    <div class="stats">
      <div class="stat">
        <div class="stat-value">${attendedConcerts.length}</div>
        <div class="stat-label">Concerts Attended</div>
      </div>
      <div class="stat">
        <div class="stat-value">$artistCount</div>
        <div class="stat-label">Artists Seen</div>
      </div>
    </div>
    <h2>Attended</h2>
    <ul class="concert-list">$rows</ul>
    $emptyState
    <p class="footer">Generated by Encore</p>
  </div>
</body>
</html>
''';
}
